// storyMap.ts — Maps episodeKey → compiled Ink JSON (bundled in the app)
//
// Key format: '{clientId}/{episodeId}'
// JSON files are generated by: node scripts/compile-ink.mjs
// In Phase 5, large stories can be fetched from S3 instead of bundled.

const STORY_MAP: Record<string, object> = {
  'duchess-margaux/ep-1': require('../../assets/clients/duchess-margaux/seasons/season-1/episodes/ep-1/script.ink.json'),
};

export function getStoryJson(clientId: string, episodeId: string): object | null {
  return STORY_MAP[`${clientId}/${episodeId}`] ?? null;
}

// Ink variable name → npcId (for syncing relationship scores to Firestore)
export const INK_VAR_TO_NPC: Record<string, string> = {
  duchess_trust:        'duchess-margaux',
  victoria_suspicion:   'victoria-cross',
  marcus_trust:         'marcus-webb',
  luna_trust:           'luna',
  commissioner_trust:   'commissioner-hayes',
  lady_ashworth_trust:  'lady-ashworth',
  prof_morley_trust:    'prof-morley',
};
