// inkdemo.tsx — Proof-of-concept: inkjs narrative engine in React Native
//
// Shows how Ink handles:
//   • Dialogue scenes (tap to advance)
//   • Choice scenes (buttons)
//   • Variables (duchess_trust, victoria_suspicion, clues)
//   • Tags driving scene type / speaker / emotion / clue grants
//   • State serialisation → Firestore save/load
//
// Run: navigate to /(main)/inkdemo from anywhere in the app
//      (add a debug button on home screen or type the route directly)

import { useRef, useState, useEffect } from 'react';
import {
  View, Text, StyleSheet, TouchableOpacity,
  SafeAreaView, ScrollView, Modal, ActivityIndicator,
} from 'react-native';
import { useRouter } from 'expo-router';
import { Story } from 'inkjs';
import { doc, getDoc, setDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '@/config/firebase';
import { useAuth } from '@/hooks/useAuth';
import { Colors } from '@/constants/colors';

// Compiled ink JSON — generated by: node scripts/compile-ink.mjs
// Re-run that script whenever duchess-ep1.ink changes
import storyJson from '../../assets/clients/duchess-margaux/seasons/season-1/episodes/ep-1/script.ink.json';

// ── Types ──────────────────────────────────────────────────────────────────

interface ParsedTags {
  scene?:   string;
  type?:    string;
  speaker?: string;
  emotion?: string;
  clues:    string[];
}

function parseTags(tags: string[]): ParsedTags {
  const r: ParsedTags = { clues: [] };
  for (const t of tags) {
    const i = t.indexOf(':');
    if (i === -1) continue;
    const key = t.slice(0, i).trim();
    const val = t.slice(i + 1).trim();
    if (key === 'scene')   r.scene   = val;
    if (key === 'type')    r.type    = val;
    if (key === 'speaker') r.speaker = val;
    if (key === 'emotion') r.emotion = val;
    if (key === 'clue')    r.clues.push(val);
  }
  return r;
}

function mergeTags(prev: ParsedTags, next: ParsedTags): ParsedTags {
  return {
    scene:   next.scene   ?? prev.scene,
    type:    next.type    ?? prev.type,
    speaker: next.speaker ?? prev.speaker,
    emotion: next.emotion ?? prev.emotion,
    clues:   next.clues,
  };
}

const NPC_NAMES: Record<string, string> = {
  'duchess-margaux': 'Duchess Margaux de Valois',
  'victoria-cross':  'Victoria Cross',
};

const EMOTION_ICON: Record<string, string> = {
  neutral:    '😐',
  happy:      '😊',
  stressed:   '😰',
  fearful:    '😨',
  angry:      '😠',
  suspicious: '🤨',
};

// ── Screen ─────────────────────────────────────────────────────────────────

export default function InkDemoScreen() {
  const { user } = useAuth();
  const router   = useRouter();

  // Ink story — created once, lives for the screen lifetime
  const storyRef = useRef<Story | null>(null);

  const [text,       setText]       = useState('');
  const [tags,       setTags]       = useState<ParsedTags>({ clues: [] });
  const [choices,    setChoices]    = useState<{ text: string; index: number }[]>([]);
  const [vars,       setVars]       = useState<Record<string, unknown>>({});
  const [cluesFound, setCluesFound] = useState<string[]>([]);
  const [complete,   setComplete]   = useState(false);
  const [saving,     setSaving]     = useState(false);
  const [showDebug,  setShowDebug]  = useState(false);
  const [saveMsg,    setSaveMsg]    = useState('');

  // ── Bootstrap ────────────────────────────────────────────────────────────
  useEffect(() => {
    async function init() {
      const story = new Story(JSON.stringify(storyJson));
      storyRef.current = story;

      // Try loading saved state from Firestore
      if (user?.uid) {
        try {
          const snap = await getDoc(doc(db, 'users', user.uid, 'inkSaves', 'duchess-ep1'));
          const saved = snap.data();
          if (saved?.stateJson) {
            story.state.LoadJson(saved.stateJson);
          }
          if (saved?.cluesFound) setCluesFound(saved.cluesFound);
        } catch (_) { /* no saved state — start fresh */ }
      }

      advance(story, { clues: [] });
    }
    init();
  }, []);

  // ── Advance story — ONE Continue() per tap, mergeTags carry-forward ──────
  function advance(story: Story, prevTags: ParsedTags = { clues: [] }, choiceIndex?: number) {
    if (choiceIndex !== undefined) story.ChooseChoiceIndex(choiceIndex);

    if (!story.canContinue && story.currentChoices.length === 0) {
      setComplete(true);
      return;
    }

    const text    = story.canContinue ? story.Continue() : '';
    const newTags = parseTags(story.currentTags ?? []);
    const active  = mergeTags(prevTags, newTags);

    // Grant clues
    if (newTags.clues.length > 0) {
      setCluesFound(prev => {
        const next = [...prev];
        newTags.clues.forEach(id => { if (!next.includes(id)) next.push(id); });
        return next;
      });
    }

    // Snapshot variables
    const vs: Record<string, unknown> = {};
    try {
      vs['duchess_trust']       = story.variablesState['duchess_trust'];
      vs['victoria_suspicion']  = story.variablesState['victoria_suspicion'];
      vs['clue_victoria_found'] = story.variablesState['clue_victoria_found'];
    } catch (_) {}
    setVars(vs);

    // Auto-skip empty lines with no choices
    if (!text.trim() && story.canContinue && story.currentChoices.length === 0) {
      advance(story, active);
      return;
    }

    if (active.type === 'episode_end') {
      setText('');
      setTags(active);
      setChoices([]);
      setComplete(true);
      return;
    }

    setText(text.trim());
    setTags(active);
    setChoices(story.currentChoices.map((c, i) => ({ text: c.text, index: i })));
  }

  // ── Save state to Firestore ───────────────────────────────────────────────
  async function saveToFirestore() {
    if (!user?.uid || !storyRef.current) return;
    setSaving(true);
    try {
      const stateJson = storyRef.current.state.ToJson();
      await setDoc(
        doc(db, 'users', user.uid, 'inkSaves', 'duchess-ep1'),
        {
          stateJson,
          cluesFound,
          savedAt: serverTimestamp(),
        },
        { merge: true }
      );
      setSaveMsg('Saved ✓');
      setTimeout(() => setSaveMsg(''), 2000);
    } catch (e) {
      setSaveMsg('Save failed ✗');
    } finally {
      setSaving(false);
    }
  }

  // ── Render ────────────────────────────────────────────────────────────────

  const isChoice   = choices.length > 0;
  const isDialogue = !isChoice && !complete;

  return (
    <SafeAreaView style={styles.safe}>

      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()}>
          <Text style={styles.back}>‹ Back</Text>
        </TouchableOpacity>
        <Text style={styles.title}>inkjs Demo</Text>
        <TouchableOpacity onPress={() => setShowDebug(true)}>
          <Text style={styles.debugBtn}>🐛</Text>
        </TouchableOpacity>
      </View>

      {/* Scene type + speaker badge */}
      <View style={styles.metaRow}>
        <View style={styles.badge}>
          <Text style={styles.badgeText}>{tags.type ?? '—'}</Text>
        </View>
        {tags.scene && (
          <Text style={styles.sceneId}># {tags.scene}</Text>
        )}
        {tags.speaker && (
          <View style={[styles.badge, { backgroundColor: Colors.accent + '22' }]}>
            <Text style={[styles.badgeText, { color: Colors.accent }]}>
              {EMOTION_ICON[tags.emotion ?? 'neutral']} {NPC_NAMES[tags.speaker] ?? tags.speaker}
            </Text>
          </View>
        )}
        {tags.clues.map(c => (
          <View key={c} style={[styles.badge, { backgroundColor: '#2a1a0a' }]}>
            <Text style={[styles.badgeText, { color: '#f5c842' }]}>🔍 {c.replace(/_/g, ' ')}</Text>
          </View>
        ))}
      </View>

      {/* Story content */}
      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>

        {/* Dialogue / narration */}
        {text ? (
          <View style={styles.dialogueBox}>
            {tags.speaker && (
              <Text style={styles.speakerName}>
                {NPC_NAMES[tags.speaker] ?? tags.speaker}
              </Text>
            )}
            <Text style={styles.dialogueText}>{text}</Text>
          </View>
        ) : null}

        {/* Choices */}
        {isChoice && (
          <View style={styles.choiceWrap}>
            <Text style={styles.choicePrompt}>What do you do?</Text>
            {choices.map(c => (
              <TouchableOpacity
                key={c.index}
                style={styles.choiceBtn}
                activeOpacity={0.75}
                onPress={() => storyRef.current && advance(storyRef.current, tags, c.index)}
              >
                <Text style={styles.choiceBtnText}>{c.text}</Text>
              </TouchableOpacity>
            ))}
          </View>
        )}

        {/* Tap to continue */}
        {isDialogue && (
          <TouchableOpacity
            style={styles.tapHint}
            onPress={() => storyRef.current && advance(storyRef.current, tags)}
          >
            <Text style={styles.tapHintText}>Tap to continue ›</Text>
          </TouchableOpacity>
        )}

        {/* Episode end */}
        {complete && (
          <View style={styles.completeBox}>
            <Text style={styles.completeIcon}>⭐</Text>
            <Text style={styles.completeTitle}>Episode Complete</Text>
            <Text style={styles.completeSub}>
              {cluesFound.length} clue{cluesFound.length !== 1 ? 's' : ''} discovered
            </Text>
          </View>
        )}

      </ScrollView>

      {/* Save button + clue count */}
      <View style={styles.footer}>
        <View style={styles.clueCount}>
          <Text style={styles.clueCountText}>🔍 {cluesFound.length} clue{cluesFound.length !== 1 ? 's' : ''}</Text>
        </View>
        <TouchableOpacity style={styles.saveBtn} onPress={saveToFirestore} disabled={saving}>
          {saving
            ? <ActivityIndicator size="small" color="#0D0D0D" />
            : <Text style={styles.saveBtnText}>{saveMsg || 'Save Progress'}</Text>
          }
        </TouchableOpacity>
      </View>

      {/* Debug modal — shows live variables + state JSON size */}
      <Modal visible={showDebug} transparent animationType="slide" onRequestClose={() => setShowDebug(false)}>
        <View style={styles.modalOverlay}>
          <View style={styles.modalCard}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>🐛 Live Variables</Text>
              <TouchableOpacity onPress={() => setShowDebug(false)}>
                <Text style={styles.modalClose}>✕</Text>
              </TouchableOpacity>
            </View>

            <Text style={styles.varLabel}>duchess_trust</Text>
            <View style={styles.varBar}>
              <View style={[styles.varFill, { width: `${Math.max(0, Math.min(100, Number(vars['duchess_trust'] ?? 50)))}%`, backgroundColor: '#4CAF50' }]} />
            </View>
            <Text style={styles.varVal}>{String(vars['duchess_trust'] ?? '—')}</Text>

            <Text style={styles.varLabel}>victoria_suspicion</Text>
            <View style={styles.varBar}>
              <View style={[styles.varFill, { width: `${Math.max(0, Math.min(100, Number(vars['victoria_suspicion'] ?? 0) + 100))}%`, backgroundColor: '#F44336' }]} />
            </View>
            <Text style={styles.varVal}>{String(vars['victoria_suspicion'] ?? '—')}</Text>

            <Text style={[styles.varLabel, { marginTop: 16 }]}>clues found</Text>
            {cluesFound.length === 0
              ? <Text style={styles.varVal}>none yet</Text>
              : cluesFound.map(c => (
                <Text key={c} style={[styles.varVal, { color: '#f5c842' }]}>• {c.replace(/_/g, ' ')}</Text>
              ))
            }

            <Text style={[styles.varLabel, { marginTop: 16 }]}>state JSON → Firestore</Text>
            <Text style={styles.varVal}>
              {storyRef.current
                ? `${(storyRef.current.state.ToJson().length / 1024).toFixed(1)} KB`
                : '—'
              }
            </Text>
            <Text style={styles.varHint}>
              This blob is written to{'\n'}
              users/&#123;uid&#125;/inkSaves/duchess-ep1{'\n'}
              and loaded on next launch to resume exactly here.
            </Text>
          </View>
        </View>
      </Modal>

    </SafeAreaView>
  );
}

// ── Styles ──────────────────────────────────────────────────────────────────
const styles = StyleSheet.create({
  safe:    { flex: 1, backgroundColor: Colors.background },

  header:  { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 8, paddingBottom: 12 },
  back:    { fontSize: 15, color: Colors.accent, fontWeight: '600' },
  title:   { fontSize: 16, fontWeight: '800', color: Colors.textLight },
  debugBtn:{ fontSize: 20 },

  metaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingHorizontal: 20, paddingBottom: 12 },
  badge:   { backgroundColor: Colors.surface, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, borderWidth: 1, borderColor: Colors.border },
  badgeText:{ fontSize: 11, color: Colors.textMuted, fontWeight: '600' },
  sceneId: { fontSize: 11, color: Colors.textMuted, alignSelf: 'center', fontFamily: 'Courier' } as any,

  content: { paddingHorizontal: 20, paddingBottom: 40, gap: 16 },

  dialogueBox: { backgroundColor: Colors.surface, borderRadius: 14, borderWidth: 1, borderColor: Colors.border, padding: 20, gap: 10 },
  speakerName: { fontSize: 12, color: Colors.accent, fontWeight: '700', letterSpacing: 1, textTransform: 'uppercase' },
  dialogueText:{ fontSize: 17, color: Colors.textLight, lineHeight: 28 },

  choiceWrap:    { gap: 10 },
  choicePrompt:  { fontSize: 11, color: Colors.textMuted, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 4 },
  choiceBtn:     { backgroundColor: Colors.surface, borderWidth: 1, borderColor: Colors.accent + '55', borderRadius: 12, padding: 16 },
  choiceBtnText: { fontSize: 15, color: Colors.textLight, lineHeight: 22 },

  tapHint:     { alignItems: 'center', paddingVertical: 20 },
  tapHintText: { fontSize: 13, color: Colors.textMuted },

  completeBox:   { alignItems: 'center', paddingVertical: 40, gap: 8 },
  completeIcon:  { fontSize: 48 },
  completeTitle: { fontSize: 22, fontWeight: '800', color: Colors.textLight },
  completeSub:   { fontSize: 14, color: Colors.textMuted },

  footer:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 12, borderTopWidth: 1, borderColor: Colors.border },
  clueCount:     {},
  clueCountText: { fontSize: 13, color: Colors.textMuted },
  saveBtn:       { backgroundColor: Colors.accent, borderRadius: 10, paddingVertical: 10, paddingHorizontal: 20, minWidth: 120, alignItems: 'center' },
  saveBtnText:   { fontSize: 14, fontWeight: '800', color: '#0D0D0D' },

  // Debug modal
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.75)', justifyContent: 'flex-end' },
  modalCard:    { backgroundColor: Colors.surface, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, gap: 6 },
  modalHeader:  { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  modalTitle:   { fontSize: 18, fontWeight: '800', color: Colors.textLight },
  modalClose:   { fontSize: 18, color: Colors.textMuted },
  varLabel:     { fontSize: 12, color: Colors.accent, fontWeight: '700', letterSpacing: 1, textTransform: 'uppercase', marginTop: 8 },
  varBar:       { height: 6, backgroundColor: Colors.border, borderRadius: 3, overflow: 'hidden', marginTop: 4 },
  varFill:      { height: '100%', borderRadius: 3 },
  varVal:       { fontSize: 14, color: Colors.textLight },
  varHint:      { fontSize: 11, color: Colors.textMuted, marginTop: 8, lineHeight: 18 },
});
